apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask-deployment
          image: MiaAcr.azurecr.io/flask:6bc49a5db847dd762f86e0e1f164e04c76de5c3c
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
